name: clean_arch_app
description: Flutter Clean Architecture with Riverpod, AutoRoute, Dio, Retrofit, Freezed
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  
  # Navigation
  auto_route: ^9.2.2
  
  # Network
  dio: ^5.7.0
  retrofit: ^4.4.1
  pretty_dio_logger: ^1.4.0
  
  # Code Generation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  
  # Utils
  dartz: ^0.10.1
  equatable: ^2.0.7
  lucide_icons: ^0.257.0
  data_table_2: ^2.6.0
  fl_chart: ^1.0.0
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  reactive_forms: ^18.1.1
  file_picker: ^10.3.2
  excel: ^4.0.6
  animate_do: ^4.2.0
  animated_text_kit: ^4.2.3
  toastification: ^3.0.3
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.4
  auto_route_generator: ^9.0.0
  riverpod_generator: ^2.6.2
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true